apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tekton-dashboard-tls
  namespace: tekton-pipelines
spec:
  secretName: tekton-dashboard-tls
  issuerRef:
    name: tekton-dev
    kind: ClusterIssuer
  dnsNames:
    - gdtek.goyoai.com