apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: goyo-harbor-dev-tls
  namespace: harbor
spec:
  secretName: goyo-harbor-dev-tls2
  duration: 8760h # 365 days
  renewBefore: 720h # 30 days before expiration
  issuerRef:
    name: goyo-harbor-dev
    kind: ClusterIssuer
  dnsNames:
    - gdharbor.goyoai.com
    - gdhb.goyoai.com