apiVersion: v1
kind: Pod
metadata:
  name: harbor-egress-test
  namespace: tekton-pipelines # Kaniko Job과 동일한 네임스페이스
spec:
  # --- 1. Kaniko Job과 동일하게 Virtual Node에 할당 ---
  nodeSelector:
    workload-type: tekton-build
  tolerations:
  - key: workload
    operator: Equal
    value: tekton-build
    effect: NoSchedule
  # ---------------------------------------------

  containers:
  - name: network-test
    image: alpine:latest # ⬅️ Git/Kaniko 이미지가 아닌 가벼운 alpine 사용
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -e
      echo "Installing 'curl' package..."
      apk add --no-cache curl
      echo "Install complete."
      echo ""

      echo "================================================="
      echo " TEST 1: GitHub.com (Control) - Port 443 (HTTPS)"
      echo " (이 테스트는 성공해야 합니다)"
      echo "================================================="
      # 10초 타임아웃으로 연결 시도
      curl -v --connect-timeout 10 https://github.com
      if [ $? -eq 0 ]; then
        echo "✓ GitHub.com (443) Succeeded."
      else
        echo "✗ GitHub.com (443) Failed!"
      fi
      echo ""

      echo "================================================="
      echo " TEST 2: Harbor LB (Target) - Port 443 (HTTPS)"
      echo " (Kaniko가 실패한 지점입니다)"
      echo "================================================="
      # 10초 타임아웃으로 연결 시도 (SSL 인증서 검증 무시)
      curl -v -k --connect-timeout 10 https://gdhb.goyoai.com
      if [ $? -eq 0 ]; then
        echo "✓ Harbor LB (443) Succeeded."
      else
        echo "✗ Harbor LB (443) Failed!"
      fi
      echo ""
      
      echo "================================================="
      echo " TEST 3: Harbor (Notary?) - Port 4443 (TCP)"
      echo " (Harbor가 푸시 시 추가로 사용할 수 있는 포트)"
      echo "================================================="
      # 10초 타임아웃으로 TCP 연결만 시도
      curl -v --connect-timeout 10 telnet://gdhb.goyoai.com:4443
      if [ $? -eq 0 ]; then
        echo "✓ Harbor (4443) Succeeded."
      else
        echo "✗ Harbor (4443) Failed!"
      fi
      echo ""

      echo "All tests complete. Pod will sleep for 1 hour."
      sleep 3600
  restartPolicy: Never