apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otlp-tls
  namespace: otlp
spec:
  secretName: otlp-tls
  issuerRef:
    name: otlp-dev 
    kind: ClusterIssuer
  dnsNames:
    - gdotlp.goyoai.com