apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-godaddy-prod
spec:
  acme:
    # Let's Encrypt Production 서버
    server: https://acme-v02.api.letsencrypt.org/directory
    email: refresh11@gmail.com
    privateKeySecretRef:
      name: letsencrypt-godaddy-prod
    solvers:
    - selector:
        dnsZones:
          - '8ai.store'
      dns01:
        webhook:
          groupName: acme.sukim.com  # Step 2에서 설정한 groupName과 동일하게
          solverName: godaddy
          config:
            apiKeySecretRef:
              name: godaddy-api-key
              key: token
            production: true  # Production API 사용
            ttl: 600