apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: langfuse-tls
  namespace: traefik
spec:
  secretName: langfuse-tls
  issuerRef:
    name: goyoai-tools
    kind: ClusterIssuer
  dnsNames:
    - gdlf.goyoai.com