---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-job-manager
  namespace: tekton-pipelines
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-ci-token-job-manager
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-job-manager
subjects:
- kind: ServiceAccount
  name: tekton-ci-token
  namespace: tekton-pipelines