apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyoai-gointern-backoffice
spec:
  template:
    spec:
      serviceAccountName: goyoai-vault-sa
      
      containers:
        - name: goyoai-gointern-backoffice-container
          volumeMounts:
            # ✅ Vault secrets 볼륨 마운트
            - name: vault-secrets
              mountPath: /vault/secrets
              readOnly: true
            - name: app-config
              mountPath: /app/config
              readOnly: true
        
        # ✅ Vault Agent Sidecar (ConfigMap 기반)
        - name: vault-agent
          image: gphb.goyoai.com/common/vault:1.21
          args:
            - agent
            - -config=/etc/vault/vault-agent.hcl
          env:
            - name: VAULT_ADDR
              value: "http://goyo-vault.vault.svc:8200"
            - name: VAULT_LOG_LEVEL
              value: "info"
            - name: VAULT_LOG_FORMAT
              value: "standard"
          volumeMounts:
            - name: vault-config
              mountPath: /etc/vault
              readOnly: true
            - name: vault-secrets
              mountPath: /vault/secrets
            - name: vault-home
              mountPath: /home/vault
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      
      volumes:
        # ✅ Vault Agent 설정 ConfigMap
        - name: vault-config
          configMap:
            name: gointern-backoffice-vault-config
        # ✅ Vault secrets 공유 볼륨
        - name: vault-secrets
          emptyDir:
            medium: Memory
        # ✅ Vault Agent 작업 디렉토리
        - name: vault-home
          emptyDir:
            medium: Memory
        - name: app-config
          configMap:
            name: gointern-backoffice-application-config