apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: goyoai-ai-server-pdb
  namespace: goyoai-web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: goyoai-ai-server-app     