apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: goyoai-web-back-pdb
  namespace: goyoai-web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: goyoai-web-back-2nd-app
      
      