apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: goyoai-web-front-pdb
  namespace: goyoai-web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: goyoai-web-front-react-app