replicas: 1

tempo:
  resources: {}
  storage:
    trace:
      backend: s3
      s3:
        bucket: tempo-bucket
        endpoint: cntwrbo3mm3p.compat.objectstorage.ap-seoul-1.oraclecloud.com
        access_key: d7ca14bc2d71e2fd440207e4eb94cb7e1fc3d767
        secret_key: "3pb/KSDvxRmbaomrBN7thTxNVD5HSRywmrReJ4hE1oA="
        insecure: false
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_binary:
          endpoint: 0.0.0.0:6832
        thrift_compact:
          endpoint: 0.0.0.0:6831
        thrift_http:
          endpoint: 0.0.0.0:14268
    opencensus: {}
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"
  securityContext: {}

serviceAccount:
  create: true
  imagePullSecrets: []
  automountServiceAccountToken: true

service:
  type: ClusterIP

persistence:
  enabled: false

nodeSelector:
  service: tools

tolerations: []

affinity: {}

# Adjustments for development environment
ingester:
  replicas: 1
  persistence:
    enabled: false # For development, you may disable persistence
  resources: {}

querier:
  replicas: 1
  resources: {}

compactor:
  replicas: 1
  resources: {}

distributor:
  replicas: 1
  resources: {}
