apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
spec:
  template:
    spec:
      containers:
        - name: ecommerce-backend-container
          command: ["/bin/sh"]
          args:
            - -c
            - |
              echo "=== Container Startup (Waiting for Vault) ==="
              
              # 1. Vault Agent Sidecar가 시크릿 파일을 생성할 때까지 대기
              while [ ! -f /vault/secrets/app.env ]; do
                echo "Waiting for Vault secrets file (/vault/secrets/app.env)..."
                sleep 2
              done
              
              echo "✅ Vault secrets file found. Sourcing environment variables..."
              
              # 2. Vault 시크릿을 환경 변수로 로드
              source /vault/secrets/app.env
              
              echo "=== Starting Go Application ==="
              
              # App 실행 (로그를 파일로 리다이렉션하여 Promtail 수집 가능하게 함)
              mkdir -p /var/log/app
              exec /entrypoint.sh 2>&1 | tee -a /var/log/app/application.log
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.otlp.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "ecommerce-backend"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=ecommerce-backend,service.namespace=ecommerce,deployment.environment=dev"
