apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
spec:
  template:
    spec:
      containers:
        - name: ecommerce-backend-container
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/app
        
        - name: promtail
          image: harbor.8ai.store/common/promtail:3.5.9
          args:
            - -config.file=/etc/promtail/promtail.yaml
            - -log.level=info
          ports:
            - name: http-metrics
              containerPort: 9080
              protocol: TCP
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/app
              readOnly: true
            - name: promtail-config
              mountPath: /etc/promtail
            - name: promtail-tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: promtail-config
          configMap:
            name: ecommerce-backend-promtail-config
        - name: promtail-tmp
          emptyDir: {}
