apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyoai-gointern-bo-web
spec:
  template:
    spec:
      containers:
        - name: goyoai-gointern-bo-web-container
          env:
            - name: NODE_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "debug"
