apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-timestamp
  namespace: tekton-pipelines
spec:
  params:
    - name: project-name
      type: string
      default: goyoai-web-prd
    - name: module-name
      type: string
    - name: author-name
      type: string
      default: "Unknown"
      description: "Git commit author name"
  results:
    - name: timestamp
      description: "Generated timestamp"

  steps:
    - name: generate-timestamp
      image: harbor.8ai.store/common/alpine:3.21
      #image: alpine
      script: |
        #!/bin/sh
        TIMESTAMP=$(TZ=Asia/Seoul date +%Y%m%d%H%M%S)
        echo -n $TIMESTAMP > $(results.timestamp.path)
        
